'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const H=require('../src/activity-hero.js');
const radar=JSON.parse(fs.readFileSync('data/activity-radar.json','utf8'));
const conf=JSON.parse(fs.readFileSync('data/activity-feature.json','utf8'));
const now=Date.parse('2026-09-25T13:00:00Z');
let n=0;
function test(name,fn){fn();n++;console.log('PASS',name)}
const event=H.events(radar,conf).find(e=>e.id==='nvidia-gtc-dc-2026');
test('select tracked official future event',()=>{assert.equal(H.select(radar,conf,now).item.id,event.id);assert.equal(H.phase(event,now),'upcoming')});
test('timezone conversion crosses the Beijing date boundary',()=>{assert.match(H.times(event).primary,/12\/02.*03:00/);assert.match(H.times(event).secondary,/12\/01.*14:00/)});
test('countdown derived from clock, not a stored 67',()=>{assert.notEqual(H.remaining(event,now),H.remaining(event,now+86400000));assert.match(H.remaining(event,Date.parse(event.start_at)-1000),/1 分钟后/)});
test('past event never retains upcoming label',()=>{assert.equal(H.phase(event,Date.parse(event.start_at)+1),'started');assert.equal(H.phase(event,Date.parse(event.start_at)+7*3600000),'ended')});
test('live requires confirmation and a bounded end',()=>{assert.notEqual(H.phase({...event,status:'live'},Date.parse(event.start_at)+1),'live');assert.equal(H.phase({...event,status:'live',end_at:'2026-12-01T21:00:00Z'},Date.parse(event.start_at)+1),'live')});
test('cancellation overrides schedule',()=>{assert.equal(H.phase({...event,status:'cancelled'},now),'unavailable');assert.equal(H.calendar({...event,status:'cancelled'},now),null)});
test('future sorted nearest, regardless of input order',()=>{const e={...radar.events[0],id:'sooner',date:'2026-10-01'};assert.equal(H.select({...radar,events:[...radar.events,e]},conf,now).item.id,'sooner')});
test('unofficial event cannot be featured',()=>{const data={...radar,sources:radar.sources.map(s=>({...s,authority:'unknown'}))};assert.notEqual(H.select(data,conf,now).kind,'event')});
test('invalid date ignored',()=>{assert.equal(H.phase({date:'2026-02-31'},now),'unknown');assert.equal(H.calendar({...event,start_at:null,date:'2026-02-31'},now),null)});
test('changed source date invalidates old reviewed metadata',()=>{const r={...radar,events:radar.events.map(e=>({...e,date:'2027-01-01'}))};assert.equal(H.events(r,conf)[0].start_at,undefined)});
test('no future falls back to recent editor selection',()=>{const f=H.select({...radar,events:[]},conf,now);assert.equal(f.kind,'media');assert.equal(f.mode,'week')});
test('old picks are never relabelled this week',()=>{const r={...radar,events:[],media_items:[{id:'p',published:'2026-09-01',url:'https://example.org/a',source_id:radar.sources.find(s=>s.authority==='official').id,editor_pick:true}]};assert.equal(H.select(r,conf,now).mode,'recent');assert.equal(H.select(r,conf,now+31*86400000).kind,'empty')});
test('malicious URL never becomes link or calendar',()=>{assert.equal(H.https('javascript:alert(1)'), '');assert.equal(H.https('https://user:pass@example.org'), '');assert.equal(H.calendar({...event,url:'javascript:alert(1)'},now),null)});
test('ICS stores verified UTC start and 15 minute local reminder',()=>{const s=H.calendar(event,now);assert.match(s,/DTSTART:20261201T190000Z/);assert.match(s,/TRIGGER:-PT15M/);assert.doesNotMatch(s,/DTEND:/);assert.match(s.replace(/\r\n[ \t]/g,''),/不会自动同步/)});
test('ICS UID stable, UTF-8 lines at most 75 bytes, correct CRLF',()=>{const s=H.calendar(event,now),t=H.calendar(event,now+1000);assert.equal(s.match(/UID:.*/)[0],t.match(/UID:.*/)[0]);for(const line of s.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);assert.equal(s.replaceAll('\r\n','').includes('\n'),false)});
test('date-only calendar invents no clock time or alarm',()=>{const s=H.calendar({...event,start_at:null},now);assert.match(s,/DTSTART;VALUE=DATE:20261201/);assert.doesNotMatch(s,/VALARM|T190000Z/)});
test('calendar text cannot inject a new property',()=>{const s=H.calendar({...event,title:'Demo\nATTENDEE:hacker@example.org'},now);assert.doesNotMatch(s,/\r\nATTENDEE:/);assert.match(s,/Demo\\nATTENDEE/)});
test('expired calendar action disabled',()=>assert.equal(H.calendar(event,Date.parse(event.start_at)+1000),null));
test('HTML escapes untrusted fields',()=>{assert.ok(H.eventHTML({...event,title:'<img onerror="alert(1)"'+'>'},now).includes('&lt;img'));assert.doesNotMatch(H.eventHTML({...event,artwork:{local:'https://evil.org/x.webp'}},now),/src="https:\/\/evil/)});
test('collapsed intro has concise description and honest RSS scope',()=>{const s=H.introHTML(radar,conf);assert.match(s,/追踪重要发布、技术深读与一手对谈/);assert.match(s,/RSS 每/);assert.match(s,/<details class="ah-rules">/);assert.doesNotMatch(s,/<details[^>]*open/)});
console.log(`Activity header: ${n} behavior tests passed`);
