'use strict';
/** @typedef {{id:string,name:string,title:string,category:string,status:string,sources:string[],reviewed:string}} Task */
const APP=JSON.parse(document.getElementById('app-data').textContent);
const {catalog:DATA,upstream:UP,site:SITE}=APP;
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PATHS={chart:'<path d="M4 3v17h17M8 15V9m5 6V5m5 10v-4"/>',reset:'<path d="M3 11a9 9 0 1 1 3 8M3 4v7h7M12 7v5l3 2"/>',moon:'<path d="M20.5 13.2A8.6 8.6 0 0 1 10.8 3.5a8.7 8.7 0 1 0 9.7 9.7z"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',table:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M3 14h18M9 4v16"/>',activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',box:'<path d="m12 3 9 5v9l-9 5-9-5V8zM3 8l9 5 9-5M12 13v9M7.5 5.5l9 5"/>',book:'<path d="M12 6v15M3 3l9 3 9-3v15l-9 3-9-3z"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 4H3v17h17v-7"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',plus:'<path d="M12 5v14M5 12h14"/>',database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',rss:'<path d="M4 10a10 10 0 0 1 10 10M4 3a17 17 0 0 1 17 17"/><circle cx="4" cy="20" r="1"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',code:'<path d="m7 6-6 6 6 6m10-12 6 6-6 6m-3-16-4 20"/>',check:'<path d="m4 12 5 5L20 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 11 3 3 5-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',compare:'<path d="M6 3v18M18 3v18M3 7l3-3 3 3m6 10 3 3 3-3M6 12h12"/>',github:'<path d="M9 21v-3c-4 1-4-2-6-2m12 5v-3.5c0-1-.3-1.5-.8-2 3-.3 6-1.4 6-6a5 5 0 0 0-1.4-3.5c.3-1 .3-2-.2-3-1.5-.2-3 1-3.5 1.4a12 12 0 0 0-6.2 0C8.4 4 7 2.8 5.5 3c-.5 1-.5 2-.2 3A5 5 0 0 0 4 9.5c0 4.6 3 5.7 6 6-.5.5-1 1.2-1 2V21"/>'};
Object.assign(PATHS,{
 sparkles:'<path d="m12 3 1.2 3.1L16 7.3l-2.8 1.2L12 12l-1.2-3.5L8 7.3l2.8-1.2z"/><path d="m18 13 .8 2.1L21 16l-2.2.9L18 19l-.8-2.1L15 16l2.2-.9z"/><path d="m5 13 .9 2.3L8 16l-2.1.7L5 19l-.9-2.3L2 16l2.1-.7z"/>',
 zap:'<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>',
 history:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',
 wrench:'<path d="M14.7 6.3a4 4 0 0 0-5 5L3 18l3 3 6.7-6.7a4 4 0 0 0 5-5l-2.5 2.5-3-3z"/>',
 layers:'<path d="m12 3 9 5-9 5-9-5zM3 12l9 5 9-5M3 16l9 5 9-5"/>',
 pill:'<path d="M8.5 4.5a4.2 4.2 0 0 1 6 0l5 5a4.2 4.2 0 0 1-6 6l-5-5a4.2 4.2 0 0 1 0-6z"/><path d="m7 12 6-6"/>',
 factory:'<path d="M3 21V10l6-4v4l6-4v5l6-3v13z"/><path d="M7 21v-4h4v4M15 15h2m-2 3h2"/>',
 cpu:'<rect x="7" y="7" width="10" height="10" rx="2"/><path d="M9 1v3m6-3v3M9 20v3m6-3v3M20 9h3m-3 6h3M1 9h3m-3 6h3"/><rect x="10" y="10" width="4" height="4"/>',
 gauge:'<path d="M4 19a9 9 0 1 1 16 0"/><path d="m12 13 4-4"/><path d="M7 19h10"/>',
 radar:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/><path d="m12 12 6-6"/>',
 newspaper:'<path d="M4 4h14v16H4z"/><path d="M8 8h6M8 12h6M8 16h4M18 8h2v10a2 2 0 0 1-2 2"/>',
 target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 flask:'<path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3"/><path d="M8 15h8"/>',
 filetext:'<path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/>',
 microscope:'<path d="m9 3 4 4-3 3-4-4zM10 10l-2 5M6 19h12M9 15a5 5 0 0 0 8 1M14 8l2 2"/>',
 trophy:'<path d="M8 4h8v5a4 4 0 0 1-8 0z"/><path d="M8 6H4v2a4 4 0 0 0 4 4m8-6h4v2a4 4 0 0 1-4 4M12 13v4M8 21h8M10 17h4"/>',
 sliders:'<path d="M4 6h10m4 0h2M4 12h4m4 0h8M4 18h8m4 0h4"/><circle cx="16" cy="6" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="14" cy="18" r="2"/>',
});
const icon=(name)=>`<svg class="ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${PATHS[name]||PATHS.external}</svg>`;
/** Apply a validated theme; visual preferences never alter other local data. */
function applyTheme(value,persist=false){
 const mode=value==='dark'?'dark':'light';
 document.documentElement.dataset.theme=mode;
 const meta=document.querySelector('meta[name="theme-color"]');
 if(meta)meta.content=mode==='dark'?'#101819':'#f5f7f4';
 const button=document.querySelector('[data-action="theme"]');
 if(button){const label=mode==='light'?'切换为深色':'切换为浅色';button.title=label;button.setAttribute('aria-label',label);button.innerHTML=icon(mode==='light'?'moon':'sun')}
 if(persist){try{localStorage.setItem('aip.theme.v2.1',mode)}catch{}}
}
function iconify(root=document){$$('[data-icon]',root).forEach(e=>{e.innerHTML=icon(e.dataset.icon);e.removeAttribute('data-icon')})}
const tasks=new Map(DATA.items.map(t=>[t.id,t])), sources=new Map(DATA.sources.map(s=>[s.id,s]));
const pages={benchmarks:['模型榜 · Benchmark','gauge'],models:['模型榜','cpu'],tibo:['Tibo 重置监控','reset'],hot:['热点榜','fire'],feed:['精选','sparkles'],progress:['AI 又能干什么了','zap'],activity:['发布会之后','history'],toolkit:['今天能跑','wrench'],topics:['全部主题','layers'],pharma:['医药与生命科学','pill'],manufacturing:['制造业','factory'],signals:['自动线索','radar'],digest:['精选简报','newspaper'],saved:['我的关注','bookmark']};
const categories=['全部',...new Set(DATA.items.map(i=>i.category))];
const kinds={all:'全部进展',release:'公开发布',research:'研究进展',upstream:'上游同步'};
const statusLabel=t=>t.status==='code'?'公开实现':'研究阶段';
let saved=new Set(),checks={},prefLayout='cards',storageOK=true;
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{storageOK=false;return fallback}}
const stored=readStore('aip.saved',[]);if(Array.isArray(stored))saved=new Set(stored.filter(id=>tasks.has(id)));
const checklistStore=readStore('aip.checks',{});if(checklistStore&&typeof checklistStore==='object'&&!Array.isArray(checklistStore))checks=checklistStore;
prefLayout=readStore('aip.layout','cards');if(!['cards','matrix'].includes(prefLayout))prefLayout='cards';
function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{storageOK=false;return false}}
const compare=new Set();let state={view:'feed',category:'全部',q:'',sort:'curated',layout:prefLayout,kind:'all',task:null,tab:'overview',topic:'all',format:'all',article:null,focus:false};
let lastMain='',toastTimer,paletteIndex=0,paletteItems=[],returnFocus=null;
const modal=$('#modal'),palette=$('#palette');
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?esc(u.href):'#'}catch{return '#'}}
function refs(ids){return ids.map(id=>{const s=sources.get(id);return s?`<a class="source-link" href="${safeLink(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.publisher)} ${icon('external')}</a>`:''}).join('')}
function sourceRows(ids){return ids.map(id=>{const s=sources.get(id);return s?`<div class="source-row"><a href="${safeLink(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ${icon('external')}</a><small>${esc(s.kind)} · 发布 ${s.published||'持续更新文档'} · 核对 ${s.checked}</small></div>`:''}).join('')}
function identity(t,owner=false){return `<div class="identity"><span class="project-mark" style="--tone:var(--${t.accent==='lime'?'accent':t.accent})">${esc(t.mark)}</span><span><span class="name">${esc(t.name)}</span>${owner?`<span class="owner">${esc(t.repo?.split('/')[0]||'Google DeepMind')}</span>`:''}</span></div>`}
function saveBtn(t){return `<button class="save ${saved.has(t.id)?'active':''}" data-action="save" data-id="${t.id}" aria-label="${saved.has(t.id)?'取消关注':'关注'} ${esc(t.name)}" aria-pressed="${saved.has(t.id)}" title="${saved.has(t.id)?'取消关注':'关注项目'}">${icon('bookmark')}</button>`}
function compareBtn(t){const yes=compare.has(t.id);return `<button class="compare-toggle ${yes?'active':''}" data-action="compare-toggle" data-id="${t.id}" aria-pressed="${yes}" aria-label="${yes?'移出对比':'加入对比'} ${esc(t.name)}"><span class="check-square">${yes?'✓':''}</span>对比</button>`}
function badge(t){return `<span class="badge ${t.status==='code'?'green':'purple'}">${icon(t.status==='code'?'code':'flask')}${statusLabel(t)}</span><span class="badge source" title="基于公开资料，尚无本站实测">${icon('filetext')}资料级</span>`}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('active');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('active'),2800)}
function writeRoute(patch={},replace=false){const next={...state,...patch};let p=new URLSearchParams();if(next.category!=='全部')p.set('category',next.category);if(next.q)p.set('q',next.q);if(next.sort!=='curated')p.set('sort',next.sort);if(next.layout==='matrix')p.set('layout','matrix');if(next.kind!=='all')p.set('kind',next.kind);if(next.topic&&next.topic!=='all')p.set('topic',next.topic);if(next.format&&next.format!=='all')p.set('format',next.format);if(next.focus)p.set('focus','1');if(next.article)p.set('article',next.article);if(next.task){p.set('task',next.task);if(next.tab!=='overview')p.set('tab',next.tab)}const h='#/'+next.view+(p.size?'?'+p.toString():'');if(replace){history.replaceState(null,'',h);parseRoute()}else if(location.hash===h){parseRoute()}else{location.hash=h;parseRoute()}}
function parseRoute(){let [v='feed',query='']=location.hash.replace(/^#\/?/,'').split('?');const p=new URLSearchParams(query);v=pages[v]?v:'feed';let topic=VTOPICS.has(p.get('topic'))?p.get('topic'):'all';if(['pharma','manufacturing'].includes(v)&&topic!=='all'&&VTOPICS.get(topic).sector!==v)topic='all';state={view:v,category:categories.includes(p.get('category'))?p.get('category'):'全部',q:(p.get('q')||'').slice(0,300),sort:['curated','name','events','sources'].includes(p.get('sort'))?p.get('sort'):'curated',layout:p.get('layout')==='matrix'?'matrix':prefLayout,kind:Object.keys(kinds).includes(p.get('kind'))?p.get('kind'):'all',task:tasks.has(p.get('task'))?p.get('task'):null,tab:['overview','timeline','run'].includes(p.get('tab'))?p.get('tab'):'overview',topic,format:['all','update','tool','reference'].includes(p.get('format'))?p.get('format'):'all',article:VARTICLES.has(p.get('article'))?p.get('article'):null,focus:p.get('focus')==='1'};renderMain();if(state.task)renderTask();else if(state.article)showArticle(state.article);else if(modal.open&&['task','article'].includes(modal.dataset.type))hideModal(false);moduleDetailsFromRoute()}
function lastEvent(id){return DATA.events.filter(e=>e.task===id).map(e=>e.date).sort().at(-1)||''}
function filteredItems(){let a=DATA.items.filter(t=>(state.view!=='saved'||saved.has(t.id))&&(state.category==='全部'||t.category===state.category)&&(!state.q||[t.name,t.title,t.category,t.summary,t.repo||''].join(' ').toLowerCase().includes(state.q.toLowerCase())));if(state.sort==='name')a.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='sources')a.sort((a,b)=>b.sources.length-a.sources.length);if(state.sort==='events')a.sort((a,b)=>lastEvent(b.id).localeCompare(lastEvent(a.id)));return a}
function renderNav(){const counts={benchmarks:BENCH.items.length,models:MODEL_DATA.boards.reduce((n,b)=>n+b.rows.length,0)+(MODEL_DATA.frontier_tracks||[]).reduce((n,t)=>n+t.items.length,0),tibo:RESET_DATA.events.length,hot:HOT.items.length,feed:VERT.articles.length,progress:DATA.items.length,activity:DATA.events.length+UP.releases.length,toolkit:DATA.items.filter(t=>t.status==='code').length,topics:VERT.topics.length,pharma:VERT.articles.filter(a=>a.sector==='pharma').length,manufacturing:VERT.articles.filter(a=>a.sector==='manufacturing').length,signals:INTAKE.items.length,digest:'01',saved:saved.size+articleSaved.size+msaved.size+bSaved.size};const groups=[['内容',['feed','hot','progress','activity','toolkit']],['垂类主题',['topics','pharma','manufacturing']],['模型',['models','tibo']],['我的工作区',['saved','signals','digest']]];const activeKey=state.view==='benchmarks'?'models':state.view;$('#nav').innerHTML=groups.map(([label,keys])=>`<div class="navgroup-label">${label}</div>${keys.map(key=>`<a href="#/${key}" class="navitem ${activeKey===key?'active':''}" ${activeKey===key?'aria-current="page"':''}>${icon(pages[key][1])}<span>${pages[key][0]}</span><small>${String(counts[key]).padStart(2,'0')}</small></a>`).join('')}`).join('');$('#crumb').textContent=pages[state.view][0];$('#source-count').textContent=DATA.sources.length+VERT.sources.length+MODEL_DATA.sources.length+RESET_DATA.sources.length+BENCH.sources.length;$('#snapshot-date').textContent=VERT.checked.replaceAll('-','.');}
function renderMain(){renderNav();if(state.view==='benchmarks'){bShow();return}if(state.view==='hot'){renderHot();return}if(MODEL_VIEWS.has(state.view)){moduleMain();return}if(['feed','topics','pharma','manufacturing','signals'].includes(state.view)){renderVerticalMain();document.body.classList.remove('nav-open');renderTray();return}$('#vertical-root').hidden=true;$('#legacy-saved').innerHTML='';$('.workspace').hidden=false;const key=[state.view,state.category,state.q,state.sort,state.layout,state.kind].join('|');if(key!==lastMain){const isHome=state.view==='progress';$('#hero').hidden=!isHome;$('#stats').hidden=!isHome;const headings={progress:['CAPABILITIES','AI 又能干什么了','zap'],activity:['THE CHANGELOG','发布之后，发生了什么','history'],toolkit:['GET STARTED','今天能跑','wrench'],digest:['SIGNAL, NOT NOISE','精选简报','newspaper'],saved:['YOUR PERSONAL INDEX','我的关注','bookmark']};$('#section-eyebrow').textContent=headings[state.view][0];$('#section-title').innerHTML=`<span class="mini-icon">${icon(headings[state.view][2])}</span><span>${esc(headings[state.view][1])}</span>`;$('#layout-buttons').hidden=!['progress','saved'].includes(state.view);$('#toolbar').hidden=state.view==='digest';$('#search').value=state.q;$('#sort').value=state.sort;$('#sort').hidden=state.view==='activity';$('#stats').innerHTML=[[DATA.items.length,'跟踪任务'],DATA.items.filter(t=>t.status==='code').length? [DATA.items.filter(t=>t.status==='code').length,'公开实现']:[0,'公开实现'],[DATA.sources.length,'原始来源'],[DATA.events.filter(e=>e.date.slice(0,7)===DATA.snapshot.slice(0,7)).length,'当月收录事件']].map(([n,l])=>`<div class="stat"><strong>${String(n).padStart(2,'0')}</strong><span>${l}</span></div>`).join('');renderFilters();renderContent();lastMain=key}if(state.view==='saved')renderSavedVertical();document.body.classList.remove('nav-open');renderTray();}
function renderFilters(){const pool=state.view==='saved'?DATA.items.filter(t=>saved.has(t.id)):DATA.items;$('#filters').innerHTML=categories.map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${c}" aria-pressed="${state.category===c}">${c}<small>${c==='全部'?pool.length:pool.filter(t=>t.category===c).length}</small></button>`).join('');$$('[data-layout]').forEach(b=>{b.classList.toggle('active',state.layout===b.dataset.layout);b.setAttribute('aria-pressed',String(state.layout===b.dataset.layout))})}
function taskCard(t){return `<article class="task-card ${compare.has(t.id)?'selected':''}" data-task-card="${t.id}"><div class="task-top">${identity(t,true)}${saveBtn(t)}</div><button class="task-title" data-action="task" data-id="${t.id}">${esc(t.title)}</button><p class="task-summary">${esc(t.summary)}</p><div class="badges">${badge(t)}<span class="badge source">${t.sources.length} 份来源</span></div><div class="task-bottom"><button class="textlink" data-action="task" data-id="${t.id}">打开档案 ${icon('arrow')}</button>${compareBtn(t)}</div></article>`}
function emptyState(){const watch=state.view==='saved';return `<div class="empty">${icon(watch?'bookmark':'search')}<h3>${watch&&!saved.size?'先关注一件你在意的事':'没有找到匹配结果'}</h3><p>${watch&&!saved.size?'点击项目右上角的书签，建立你的进度列表。':'换个关键词，或清除当前筛选。'}</p><button class="button" data-action="${watch&&!saved.size?'discover':'reset'}">${watch&&!saved.size?'浏览项目':'清除筛选'} ${icon('arrow')}</button>${watch&&!saved.size?'<button class="plain" data-action="import" style="margin-left:16px">导入关注</button>':''}</div>`}
function renderContent(){const items=filteredItems();let html='';const num=items.length;$('#contextline').hidden=false;if(state.view==='activity'){renderActivity();return}if(state.view==='digest'){renderDigest();return}$('#contextline').innerHTML=`<span>${num} 个${state.view==='toolkit'?'匹配项目':'任务'}<span class="footer-divider">/</span>${state.view==='toolkit'?'官方上手路径，命令未在本站执行':'按任务组织，不代表职业替代程度'}</span>${state.view==='saved'?'<span><button data-action="import">导入</button> · <button data-action="export-saved">导出关注</button></span>':'<button data-action="about" title="阅读证据标注规则">资料级 '+icon('info')+'</button>'}`;
if(state.view==='toolkit'){const tools=items.filter(t=>t.status==='code');$('#contextline').firstElementChild.textContent=`${tools.length} 个工具 / 官方上手路径，命令未在本站执行`;html=tools.length?`<div class="tool-grid">${tools.map(t=>`<article class="tool-card"><div class="task-top">${identity(t)}<span class="badge">${t.effort}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.requirements)}</p><div class="tool-foot"><span>验收清单 ${t.checks.length} 项</span><button class="button" data-action="run" data-id="${t.id}">查看上手路径 ${icon('arrow')}</button></div></article>`).join('')}</div>`:emptyState();}
else if(!items.length)html=emptyState();
else if(state.layout==='matrix')html=`<div class="table-wrap"><table class="matrix"><thead><tr><th>任务 / 项目</th><th>领域</th><th>可用状态</th><th>证据</th><th>最近收录事件</th><th>操作</th></tr></thead><tbody>${items.map(t=>`<tr><td>${identity(t)}<button class="task-title" data-action="task" data-id="${t.id}">${esc(t.title)}</button></td><td class="mini">${t.category}</td><td><span class="badge ${t.status==='code'?'green':'purple'}">${statusLabel(t)}</span></td><td class="mini">资料级 · ${t.sources.length} 来源</td><td class="mini mono">${lastEvent(t.id)||'—'}</td><td><div class="table-actions">${saveBtn(t)}${compareBtn(t)}</div></td></tr>`).join('')}</tbody></table></div>`;
else html=`<div class="cards">${items.map(taskCard).join('')}</div>`;
$('#content').innerHTML=html;}
function selectedEvents(){const raw=UP.releases.map(e=>({...e,kind:'upstream',date:e.published_at.slice(0,10),summary:'上游发布元数据；尚未评估其能力变化。'}));const q=state.q.toLowerCase();return [...DATA.events,...raw].filter(e=>{const t=tasks.get(e.task);return t&&(state.category==='全部'||t.category===state.category)&&(state.kind==='all'||e.kind===state.kind)&&(!q||[e.title,e.summary,e.date,t.name,t.title,t.category].join(' ').toLowerCase().includes(q))}).sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id))}
function eventHTML(e){const t=tasks.get(e.task);return `<article class="event"><div class="meta"><span style="color:var(--text)">${esc(t?.name||e.repo)}</span><span class="badge ${e.kind==='research'?'purple':''}">${kinds[e.kind]||'上游发布'}</span>${e.kind==='upstream'?'<span>未评估</span>':''}</div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p>${e.delta?`<div class="delta"><b>变化</b>${esc(e.delta)}</div>`:''}<div class="event-bottom"><span class="sources">${e.sources?refs(e.sources):`<a class="source-link" href="${safeLink(e.url)}" target="_blank" rel="noopener noreferrer">原始发布 ${icon('external')}</a>`}</span><button class="textlink" data-action="task" data-id="${e.task}">项目档案 ${icon('arrow')}</button></div></article>`}
function renderActivity(){const events=selectedEvents();$('#contextline').innerHTML=`<div class="feed-filter">${Object.entries(kinds).map(([k,v])=>`<button class="chip ${state.kind===k?'active':''}" data-kind="${k}">${v}</button>`).join('')}</div><span>${events.length} 条记录</span>`;if(!events.length){$('#content').innerHTML=state.kind==='upstream'?'<div class="empty">'+icon('activity')+'<h3>还没有上游同步记录</h3><p>采集脚本已提供，尚未在联网环境完成运行。</p><button class="button" data-action="about">查看数据状态</button></div>':emptyState();return}const groups={};events.forEach(e=>(groups[e.date]??=[]).push(e));$('#content').innerHTML=Object.entries(groups).map(([date,list])=>`<div class="date-group"><div class="date-column">${date.replaceAll('-','.')}<span>EVENT DATE</span></div><div class="event-list">${list.map(eventHTML).join('')}</div></div>`).join('')}
function digestEvents(){const start=DATA.snapshot.slice(0,7);return DATA.events.filter(e=>e.date.slice(0,7)===start).sort((a,b)=>b.date.localeCompare(a.date))}
function digestText(){return `# AI坐标 · 精选简报 001\n\n编选日期：${DATA.snapshot}。这是资料编选，不是完整行业榜单。\n\n${digestEvents().map((e,i)=>`## ${String(i+1).padStart(2,'0')} ${tasks.get(e.task).name}：${e.title}\n\n事件日期：${e.date}\n\n${e.summary}\n\n编辑解读：${e.delta}\n\n来源：${e.sources.map(id=>sources.get(id).url).join('\n')}\n\n状态：公开资料，本站未复测。`).join('\n\n')}\n\n## 继续跟踪\n\n${DATA.items.filter(t=>['graphrag','alphaevolve'].includes(t.id)).map(t=>`- ${t.name}：${t.boundary} 来源：${sources.get(t.sources[0]).url}`).join('\n')}\n`}
function renderDigest(){$('#contextline').hidden=true;$('#content').innerHTML=`<div class="digest-layout"><section class="digest"><div class="eyebrow">FIELD NOTES / ISSUE 001</div><h2>少一点发布噪声。<br>多一点实际变化。</h2><p class="intro">${DATA.snapshot.replaceAll('-','.')} 编选 · 当月收录的 ${digestEvents().length} 条进展，不代表全行业动态。</p>${digestEvents().map((e,i)=>`<article><h3><code>${String(i+1).padStart(2,'0')}</code>${esc(tasks.get(e.task).name)}：${esc(e.title)}</h3><p>${esc(e.summary)}</p><p style="margin-top:10px">${esc(e.delta)}</p><div class="event-bottom"><span class="sources">${refs(e.sources)}</span><span>${e.date}</span></div></article>`).join('')}<div class="detail-notice">来源为官方发布，尚无本站复测。历史研究另见更新记录。</div></section><aside class="digest-side"><div class="side-panel"><h3>带走这一期</h3><p>分享链接，或导出 Markdown 继续编辑。</p><button class="button primary" data-action="digest-export">${icon('download')} 导出简报</button><button class="button" data-action="share-page">${icon('copy')} 复制页面链接</button></div><div class="side-panel"><h3>接下来跟踪什么</h3><p>GraphRAG 的冲突处理，AlphaEvolve 的开放条件。没有新证据，不自动升级结论。</p><a class="button" href="#/activity">查看全部进展 ${icon('arrow')}</a></div></aside></div>`}
function renderTray(){const ids=[...compare].filter(id=>tasks.has(id));const tray=$('#compare-tray');tray.hidden=!ids.length;tray.innerHTML=`<span class="count">${ids.length} / 3</span><span class="compare-names">${ids.map(id=>esc(tasks.get(id).name)).join(' · ')}</span><button class="button primary small" data-action="compare" ${ids.length<2?'disabled':''}>对比项目 ${icon('arrow')}</button><button class="iconbutton" data-action="compare-clear" title="清空对比" aria-label="清空对比">${icon('close')}</button>`}
function showModal(label,html,type='info',wide=false){if(!modal.open)returnFocus=document.activeElement;modal.dataset.type=type;modal.className=['task','article','model','reset-record'].includes(type)?'drawer':wide?'wide':'';$('#modal-label').textContent=label;$('#modal-body').innerHTML=html;if(!modal.open)modal.showModal();document.body.style.overflow='hidden';modal.scrollTop=0;}
function hideModal(routeToo=true){modal.close();document.body.style.overflow='';if(routeToo&&MODEL_VIEWS.has(state.view)&&(mParams().get('model')||mParams().get('event')))mRoute({model:null,event:null},true);if(routeToo&&(state.task||state.article))writeRoute({task:null,article:null,tab:'overview'});if(returnFocus&&document.contains(returnFocus))returnFocus.focus({preventScroll:true})}
function taskTimeline(t){const ev=DATA.events.filter(e=>e.task===t.id).sort((a,b)=>b.date.localeCompare(a.date));return ev.length?ev.map(e=>`<div style="margin:20px 0 8px" class="mono muted">${e.date}</div>${eventHTML(e)}`).join(''):'<div class="timeline-empty">还没有收录带明确日期的事件。公开仓库的存在不自动等于新的进展。</div>'}
function taskRun(t){return `<section class="detail-section"><h3>${icon('box')} 环境与准备</h3><p>${esc(t.requirements)}</p></section>${t.command?`<div class="codebox"><div class="codehead"><span>SHELL / 官方路径，未执行</span><button data-action="copy-command" data-id="${t.id}">复制 ${icon('copy')}</button></div><pre>${esc(t.command)}</pre></div>`:''}<section class="detail-section"><h3>${icon('code')} 建议任务</h3><p>${esc(t.test)}</p></section><section class="detail-section"><h3>${icon('check')} 本机验收清单</h3><div class="checklist">${t.checks.map((c,i)=>{const yes=Boolean(checks[t.id]?.includes(i));return `<label class="${yes?'done':''}"><input type="checkbox" data-check-task="${t.id}" data-check-index="${i}" ${yes?'checked':''}>${esc(c)}</label>`}).join('')}</div><p class="detail-notice">勾选仅记录你的检查状态，不会改变网站的证据等级。</p></section><div class="action-row"><a class="button primary" href="${safeLink(sources.get(t.sources[0]).url)}" target="_blank" rel="noopener noreferrer">官方文档 ${icon('external')}</a><button class="button" data-action="contribute" data-id="${t.id}">提交复现记录</button></div>`}
function renderTask(){const t=tasks.get(state.task);if(!t)return;let body='';if(state.tab==='overview')body=`<section class="detail-section"><h3>${icon('book')} 已有证据</h3><p>${esc(t.scope)}</p><div class="sources" style="margin-top:12px">${refs(t.sources)}</div></section><section class="detail-section boundary"><h3>仍需验证</h3><p>${esc(t.boundary)}</p></section><section class="detail-section"><h3>${icon('check')} 怎样检验 · 编辑建议</h3><p>${esc(t.test)}</p></section><div class="action-row"><button class="button primary" data-action="run" data-id="${t.id}">${t.status==='code'?'查看上手路径':'查看研究入口'} ${icon('arrow')}</button>${compareBtn(t)}</div><details class="source-accordion"><summary>原始来源 <span class="muted">${t.sources.length}</span></summary>${sourceRows(t.sources)}</details><div class="details-label"><span>资料核对 ${t.reviewed}</span><span>本站未复测</span></div>`;if(state.tab==='timeline')body=taskTimeline(t);if(state.tab==='run')body=taskRun(t);showModal('TASK / '+t.name,`<div class="detail-header">${identity(t,true)}<div class="detail-actions">${saveBtn(t)}<button class="iconbutton" data-action="share-page" title="复制档案链接" aria-label="复制档案链接">${icon('external')}</button></div></div><h2 id="modal-title">${esc(t.title)}</h2><p class="dialog-intro">${esc(t.summary)}</p><div class="badges"><span class="badge">${t.category}</span>${badge(t)}</div><div class="detail-tabs">${[['overview','概览'],['timeline','事件'],['run','上手']].map(([key,title])=>`<button class="detail-tab ${state.tab===key?'active':''}" data-task-tab="${key}">${title}</button>`).join('')}</div>${body}`,'task')}
function openCompare(){if(compare.size<2)return;const ts=[...compare].map(id=>tasks.get(id));const rows=[['领域',t=>t.category],['任务',t=>t.title],['公开状态',t=>statusLabel(t)],['证据',t=>`${t.evidence} · 本站未复测`],['适用范围',t=>t.scope],['尚待验证',t=>t.boundary],['运行环境',t=>t.requirements],['成本',()=> '未实测'],['最近收录事件',t=>lastEvent(t.id)||'暂无'],['核对日期',t=>t.reviewed]];showModal('COMPARE / '+ts.length+' PROJECTS',`<h2 id="modal-title">把边界放在一起看。</h2><p class="dialog-intro">这是条件对比，不是统一能力排名。不同任务不合成一个总分。</p><table class="compare-table"><thead><tr><th>项目</th>${ts.map(t=>`<td>${esc(t.name)}</td>`).join('')}</tr></thead><tbody>${rows.map(([name,f])=>`<tr><th>${name}</th>${ts.map(t=>`<td>${esc(f(t))}</td>`).join('')}</tr>`).join('')}<tr><th>来源</th>${ts.map(t=>`<td><a class="source-link" href="${safeLink(sources.get(t.sources[0]).url)}" target="_blank" rel="noopener noreferrer">官方资料 ${icon('external')}</a></td>`).join('')}</tr></tbody></table><div class="action-row"><button class="button" data-action="export-compare">导出 Markdown ${icon('download')}</button></div>`,'info',true)}
function about(){showModal('ABOUT / DATA & METHOD',`<div class="eyebrow">AI PROGRESS / ${esc(SITE.version)}</div><h2 id="modal-title">进展，不是热度。</h2><p class="dialog-intro">以任务为索引，保留来源和历史变化。首页保持简单，判断依据在档案里展开。</p><div class="about-grid"><div class="about-panel"><h3>公开实现 ≠ 可靠完成</h3><p>公开实现表示查到代码与使用文档；研究阶段表示本次只核对研究资料，不能推断当前访问权限。</p></div><div class="about-panel"><h3>资料级 ≠ 实测</h3><p>现有条目基于官方或作者资料，本站实测为 0。上游版本更新也不会自动升级能力结论。</p></div><div class="about-panel"><h3>事件时间 ≠ 核对时间</h3><p>旧发布保留旧日期；核对日期只说明何时查阅资料，不把历史研究改写成今日新闻。</p></div><div class="about-panel"><h3>本地优先</h3><p>关注、主题和验收清单保存在浏览器。没有账号登录、追踪脚本或自动上传；导入导出可备份个人列表。</p></div></div><h3 style="font-size:13px;margin:25px 0 7px">当前数据状态</h3><div class="health-row"><span>原有任务档案核对</span><span>${DATA.snapshot}</span></div><div class="health-row"><span>原有任务版本同步</span><span>${esc(UP.last_success||'尚未运行')}</span></div><div class="health-row"><span>已记录同步错误</span><span>${UP.errors.length}</span></div><div class="health-row"><span>垂类资料核对</span><span>${VERT.checked} / ${VERT.articles.length} 条资料</span></div><div class="health-row"><span>主题线索采集成功</span><span>${esc(INTAKE.last_success||'尚未运行')}</span></div><div class="health-row"><span>当前仓库</span><span>${esc(SITE.repository||'未绑定')}</span></div><div class="health-row"><span>RSS 地址</span><span>${SITE.base_url?'已配置':'待部署后生成'}</span></div><div class="action-row"><button class="button" data-action="sources">浏览全部来源</button><button class="button" data-va="sync">主题更新状态</button><button class="button" data-action="data">导出数据 ${icon('download')}</button></div><p class="detail-notice">公开数据集只有 ${DATA.items.length} 个种子任务，不是完整行业覆盖。脚本与发布配置已随源码交付；本地代码完成不表示线上服务已经运行。</p>`)}
function allSources(){showModal('SOURCES / '+DATA.sources.length,`<h2 id="modal-title">让每个结论有出处。</h2><p class="dialog-intro">来源核对与软件运行分开记录。展开原始发布查看完整范围。</p>${sourceRows(DATA.sources.map(s=>s.id))}`)}
function repoInfo(){if(SITE.repository){window.open('https://github.com/'+SITE.repository,'_blank','noopener,noreferrer');return}showModal('REPOSITORY / NOT CONNECTED',`<h2 id="modal-title">还没有绑定发布仓库。</h2><p class="dialog-intro">此版本不预设账号，也不会尝试读取你的浏览器登录状态。仓库在部署配置中确定，前端不保存访问令牌。</p><div class="codebox"><div class="codehead">本地构建配置示例</div><pre>python scripts/build.py \\\n  --repo YOUR_ACCOUNT/ai-progress \\\n  --base-url https://YOUR_ACCOUNT.github.io/ai-progress/</pre></div><p class="detail-notice">GitHub Pages 工作流会根据实际仓库自动填充这些值。详见源码中的 docs/DEPLOY.md。</p>`)}
function subscribe(){const url=SITE.base_url?SITE.base_url+'feed.xml':null;showModal('SUBSCRIBE / RSS',`<h2 id="modal-title">只跟有变化的事。</h2><p class="dialog-intro">RSS 供阅读器订阅已编选事件；我的关注保存在本机，不发送邮件。</p>${url?`<div class="codebox"><pre>${esc(url)}</pre></div><div class="action-row"><button class="button primary" data-action="copy-feed">复制 RSS 地址 ${icon('copy')}</button><a class="button" href="${safeLink(url)}" target="_blank" rel="noopener noreferrer">打开 RSS ${icon('external')}</a></div>`:`<div class="about-panel"><h3>RSS 生成已接入构建流程</h3><p>正式部署并配置站点地址后，构建会生成 feed.xml。当前没有公开订阅地址，不创建空订阅或收集邮箱。</p></div>`}<div class="action-row"><button class="button" data-action="export-saved">备份我的关注</button><button class="button" data-action="import">导入关注列表</button></div>`)}
function contribute(id=''){showModal('CONTRIBUTE / EVIDENCE FIRST',`<h2 id="modal-title">提交一个值得跟踪的变化。</h2><p class="dialog-intro">${SITE.repository?'生成 GitHub Issue 草稿，由你检查后提交。':'先保存为本地草稿；绑定仓库后可直接前往 GitHub 提交。'}</p><form id="contribute-form"><label class="field">关联任务<select name="task">${DATA.items.map(t=>`<option value="${t.id}" ${t.id===id?'selected':''}>${esc(t.name)} / ${esc(t.title)}</option>`).join('')}<option value="new">新增任务</option></select></label><label class="field">变化标题<input name="title" required maxlength="140" placeholder="例如：新增公开入口或独立复现结果"></label><label class="field">原始来源<input name="source" type="url" required maxlength="2048" placeholder="https://…"></label><div class="field-row"><label class="field">事件日期（未知可留空）<input name="date" type="date" max="${new Date().toISOString().slice(0,10)}"></label><label class="field">证据类型<select name="kind"><option>官方发布</option><option>作者研究</option><option>独立复现</option><option>我的实测</option></select></label></div><label class="field">证据与限制<textarea name="notes" required maxlength="3000" placeholder="支持什么结论？不能证明什么？实测请补充环境、成本与日志。"></textarea></label><p class="detail-notice">不要提交密钥、隐私或未获授权的企业资料。仅生成草稿，不会自动发送。</p><div class="action-row"><button class="button primary" type="submit">${SITE.repository?'检查 GitHub 草稿':'导出线索草稿'} ${icon('arrow')}</button></div></form>`)}
function shortcuts(){showModal('KEYBOARD / SHORTCUTS',`<h2 id="modal-title">少点几次鼠标。</h2>${[['⌘ / Ctrl + K','全局搜索与跳转'],['/','搜索当前列表'],['↑ / ↓','在命令面板中选择'],['Enter','打开选中结果'],['Esc','关闭弹窗'],['?','查看快捷键']].map(([k,l])=>`<div class="health-row"><span>${l}</span><kbd>${k}</kbd></div>`).join('')}`)}
function download(filename,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('已导出 '+filename)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制')}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.cssText='position:fixed;opacity:0';const parent=modal.open?$('#modal-body'):document.body;parent.appendChild(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();if(ok)toast('已复制');else download('ai-progress-copy.txt',text)}}
function sharePage(){if(SITE.base_url){copyText(SITE.base_url+location.hash);return}if(/^https?:$/.test(location.protocol)&&!['127.0.0.1','localhost'].includes(location.hostname)){copyText(location.href);return}const t=tasks.get(state.task);download(t?'task-'+t.id+'.md':'ai-progress-link.txt',t?`# ${t.name} · ${t.title}\n\n${t.summary}\n\n待验证：${t.boundary}\n\n来源：${t.sources.map(id=>sources.get(id).url).join('\n')}\n\n核对 ${t.reviewed}；本站未实测。\n本地定位：${location.hash}`:`当前为本地版本，暂无公开分享链接。\n页面定位：${location.hash}`)}
function exportCompare(){const ts=[...compare].map(id=>tasks.get(id));const text=`# 项目条件对比\n\n不是统一能力评分。资料核对 ${DATA.snapshot}；本站未实测。\n\n| 条件 | ${ts.map(t=>t.name).join(' | ')} |\n| --- | ${ts.map(()=> '---').join(' | ')} |\n${[['任务',t=>t.title],['范围',t=>t.scope],['待验证',t=>t.boundary],['环境',t=>t.requirements],['来源',t=>sources.get(t.sources[0]).url]].map(([l,f])=>`| ${l} | ${ts.map(t=>String(f(t)).replaceAll('|','\\|')).join(' | ')} |`).join('\n')}`;download('ai-progress-compare.md',text)}
function exportView(){if(['feed','topics','pharma','manufacturing','signals'].includes(state.view))return exportVertical();if(state.view==='digest')return download('ai-progress-001.md',digestText());const data=state.view==='activity'?selectedEvents():filteredItems().filter(t=>state.view!=='toolkit'||t.status==='code');download('ai-progress-'+state.view+'.json',JSON.stringify({snapshot:DATA.snapshot,view:state.view,items:data,sources:DATA.sources},null,2),'application/json;charset=utf-8')}
function refreshCards(){lastMain='';renderMain();if(state.task)renderTask()}
function changeSaved(id){if(!tasks.has(id))return;saved.has(id)?saved.delete(id):saved.add(id);const ok=store('aip.saved',[...saved]);renderNav();if(state.view==='saved'){refreshCards()}else{$$(`.save[data-id="${id}"]`).forEach(b=>b.outerHTML=saveBtn(tasks.get(id)))}toast(ok?(saved.has(id)?'已加入我的关注':'已取消关注'):'关注仅在本次会话有效；可导出备份')}
function paletteOpen(){if(modal.open)return;paletteIndex=0;$('#palette-input').value='';renderPalette();palette.showModal();document.body.style.overflow='hidden';$('#palette-input').focus()}
function renderPalette(){const q=$('#palette-input').value.toLowerCase().trim();paletteItems=[...BENCH.items.map(b=>({title:b.name+' · '+b.subtitle,id:b.id,type:'benchmark',icon:'benchmark',sub:BGROUPS.get(b.group).title})),...Object.entries(pages).map(([id,[title,i]])=>({title,id,type:'page',icon:i,sub:'页面'})),...DATA.items.map(t=>({title:t.name+' · '+t.title,id:t.id,type:'task',icon:'box',sub:t.category})),...VERT.topics.map(t=>({title:t.title,id:t.id,type:'topic',icon:'grid',sub:VSECTORS.get(t.sector).title})),...VERT.articles.map(a=>({title:a.title,id:a.id,type:'article',icon:'book',sub:VSECTORS.get(a.sector).short}))].filter(x=>[x.title,x.sub].join(' ').toLowerCase().includes(q));paletteIndex=Math.min(paletteIndex,Math.max(0,paletteItems.length-1));$('#palette-results').innerHTML=paletteItems.length?paletteItems.map((r,i)=>`<button class="palette-item ${i===paletteIndex?'active':''}" data-palette-index="${i}">${icon(r.icon)}<span>${esc(r.title)}</span><small>${r.sub}</small></button>`).join(''):'<div class="timeline-empty">没有匹配结果</div>'}
function paletteSelect(index){const r=paletteItems[index];if(!r)return;palette.close();document.body.style.overflow='';if(r.type==='benchmark'){history.pushState(null,'','#/benchmarks?bench='+encodeURIComponent(r.id));parseRoute()}else if(r.type==='page')writeRoute({view:r.id,q:'',category:'全部',task:null,article:null,topic:'all',format:'all',focus:false,tab:'overview'});else if(r.type==='topic')writeRoute({view:VTOPICS.get(r.id).sector,topic:r.id,q:'',task:null,article:null});else if(r.type==='article')writeRoute({view:VARTICLES.get(r.id).sector,article:r.id,task:null});else writeRoute({task:r.id,article:null,tab:'overview'})}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat)return writeRoute({category:cat.dataset.category,task:null});const layout=e.target.closest('[data-layout]');if(layout){prefLayout=layout.dataset.layout;store('aip.layout',prefLayout);return writeRoute({layout:prefLayout},true)}const kind=e.target.closest('[data-kind]');if(kind)return writeRoute({kind:kind.dataset.kind});const tab=e.target.closest('[data-task-tab]');if(tab)return writeRoute({tab:tab.dataset.taskTab},true);const pr=e.target.closest('[data-palette-index]');if(pr)return paletteSelect(Number(pr.dataset.paletteIndex));const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
if(a==='task'||a==='run')return writeRoute({task:id,tab:a==='run'?'run':'overview'});
if(a==='save')return changeSaved(id);
if(a==='compare-toggle'){if(compare.has(id))compare.delete(id);else if(compare.size<3)compare.add(id);else return toast('最多对比 3 个项目');refreshCards();return}
if(a==='compare-clear'){compare.clear();return refreshCards()}if(a==='compare')return openCompare();if(a==='export-compare')return exportCompare();
if(a==='close-modal')return hideModal();if(a==='about')return about();if(a==='sources')return allSources();if(a==='repo')return repoInfo();if(a==='subscribe')return subscribe();if(a==='contribute')return contribute(id);if(a==='shortcuts')return shortcuts();if(a==='command')return paletteOpen();
if(a==='data')return download('ai-progress-data.json',JSON.stringify({catalog:DATA,upstream:UP},null,2),'application/json;charset=utf-8');if(a==='export-view')return exportView();if(a==='digest-export')return download('ai-progress-001.md',digestText());if(a==='copy-feed'&&SITE.base_url)return copyText(SITE.base_url+'feed.xml');if(a==='share-page')return sharePage();if(a==='copy-command')return copyText(tasks.get(id)?.command||'');
if(a==='export-saved')return download('ai-progress-collection.json',JSON.stringify({version:1,saved:[...saved],checks,exported_at:new Date().toISOString()},null,2),'application/json;charset=utf-8');if(a==='import'){$('#import-file').click();return}
if(a==='reset')return writeRoute({q:'',category:'全部',kind:'all'});if(a==='discover')return writeRoute({view:'progress',q:'',category:'全部',task:null});
if(a==='theme'){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark',true);return}
if(a==='menu'){document.body.classList.add('nav-open');return}if(a==='close-nav')document.body.classList.remove('nav-open');
});
$('#search').addEventListener('input',e=>{const pos=e.target.selectionStart;state.q=e.target.value;writeRoute({q:e.target.value},true);$('#search').focus({preventScroll:true});try{$('#search').setSelectionRange(pos,pos)}catch{}});
$('#sort').addEventListener('change',e=>writeRoute({sort:e.target.value},true));
$('#palette-input').addEventListener('input',()=>{paletteIndex=0;renderPalette()});
document.addEventListener('change',e=>{if(!e.target.matches('[data-check-task]'))return;const id=e.target.dataset.checkTask,index=Number(e.target.dataset.checkIndex);const list=new Set(Array.isArray(checks[id])?checks[id]:[]);e.target.checked?list.add(index):list.delete(index);checks[id]=[...list];const ok=store('aip.checks',checks);e.target.closest('label').classList.toggle('done',e.target.checked);if(!ok)toast('检查清单仅在本次会话有效')});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>256*1024)return toast('文件超过 256 KB，无法导入');try{const obj=JSON.parse(await file.text());if(obj.version!==1||!Array.isArray(obj.saved)||obj.saved.length>1000||!obj.saved.every(s=>typeof s==='string'))throw Error();obj.saved.filter(s=>tasks.has(s)).forEach(s=>saved.add(s));if(obj.checks&&typeof obj.checks==='object'&&!Array.isArray(obj.checks))for(const [id,list] of Object.entries(obj.checks)){if(tasks.has(id)&&Array.isArray(list))checks[id]=[...new Set(list.filter(n=>Number.isInteger(n)&&n>=0&&n<tasks.get(id).checks.length))]}const ok=store('aip.saved',[...saved])&&store('aip.checks',checks);refreshCards();toast(ok?'已合并关注和验收清单':'已导入；浏览器不允许持久保存')}catch{toast('文件格式不正确，请使用本站导出的关注文件')}});
document.addEventListener('submit',e=>{if(e.target.id!=='contribute-form')return;e.preventDefault();const f=new FormData(e.target);const title=String(f.get('title')).trim(),notes=String(f.get('notes')).trim();let url;try{url=new URL(String(f.get('source')));if(!['http:','https:'].includes(url.protocol))throw Error()}catch{return toast('来源必须是 http 或 https 链接')}if(!title||!notes)return toast('请填写标题和证据');const body=`## 关联任务\n${f.get('task')}\n\n## 来源\n${url.href}\n\n## 事件日期\n${f.get('date')||'未知'}\n\n## 证据类型\n${f.get('kind')}\n\n## 证据与限制\n${notes}\n\n---\n待维护者核验；此草稿不自动改变能力状态。`;if(SITE.repository){const issue=new URL('https://github.com/'+SITE.repository+'/issues/new');issue.searchParams.set('title','[线索] '+title);issue.searchParams.set('body',body);window.open(issue.href,'_blank','noopener,noreferrer');toast('已打开草稿，请在 GitHub 检查后提交')}else download('ai-progress-evidence.md','# '+title+'\n\n'+body)});
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(palette.open)palette.close();else paletteOpen();return}if(palette.open){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();paletteIndex=(paletteIndex+(e.key==='ArrowDown'?1:-1)+Math.max(1,paletteItems.length))%Math.max(1,paletteItems.length);renderPalette();$('.palette-item.active')?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'){e.preventDefault();paletteSelect(paletteIndex)}return}if(!typing&&!modal.open){if(e.key==='/'){e.preventDefault();if(state.view==='digest')writeRoute({view:'progress'});($('#b-search')||$('#m-search')||$('#r-search')||$('#v-search')||$('#search'))?.focus()}if(e.key==='?'){e.preventDefault();shortcuts()}}if(e.key==='Escape')document.body.classList.remove('nav-open')});
modal.addEventListener('cancel',e=>{e.preventDefault();hideModal()});modal.addEventListener('close',()=>{document.body.style.overflow=''});palette.addEventListener('close',()=>{document.body.style.overflow=''});
for(const d of [modal,palette])d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){if(d===modal)hideModal();else d.close()}});
function renderFeature(){const e=[...DATA.events].sort((a,b)=>b.date.localeCompare(a.date))[0];if(!e)return;const t=tasks.get(e.task);const el=$('.featured');el.dataset.id=t.id;el.innerHTML=`<div class="feature-grid" aria-hidden="true"></div><div class="feature-top"><span><i class="state-dot"></i> 近期收录</span><code>${e.date.replaceAll('-','.')}</code></div><div class="feature-center"><span class="feature-symbol" style="color:var(--${t.accent==='lime'?'accent':t.accent})">${esc(t.mark)}</span><div><h2>${esc(t.name)} <span>${esc(e.tag||'')}</span></h2><p>${esc(e.short_title||e.title)}</p></div></div><div class="feature-bottom"><span>查看原始发布与边界</span>${icon('arrow')}</div>`}
/* Bootstrap is emitted after the topic module. */
