'use strict';
(()=>{
let loading=false;
const strengthLabel={high:'强',medium:'中',low:'低'};
const semanticLabel={timing_hint:'时间暗示',explicit_announcement:'明确预告',reset_executed:'已执行表述',propagation_complete:'传播完成',banked_delivery:'重置卡发放',banked_announcement:'重置卡预告',usage_explanation:'用量/修复解释',denial:'否认/纠正',reset_related:'重置相关'};
function when(x){const raw=x.published_at||x.observed_at||'';if(raw){try{return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(raw))+' 北京时间'}catch{}}return x.date||'时间未核验'}
function signalRows(){const events=RESET_DATA.events.filter(x=>x.interpretation||x.original_text).map(x=>({...x,_source:'event'}));const inbox=(RESET_DATA.inbox||[]).filter(x=>x.interpretation).map(x=>({...x,_source:'inbox',title:x.title||'Tibo 新帖候选',original_text:x.excerpt,not_proves:x.not_proves||x.reason}));return [...events,...inbox].sort((a,b)=>String(b.published_at||b.date||'').localeCompare(String(a.published_at||a.date||''))).slice(0,8)}
function intelBlock(){const rows=signalRows();if(!rows.length)return '';return '<section class="tibo-intel"><div class="tibo-intel-head"><div><p class="eyebrow">TIBO / CONTEXT FIRST</p><h2>先读他说了什么，再判断是不是 Reset。</h2><p>回复、玩笑和时间暗示必须连同上文理解；只有明确执行或官方说明才会升级为确认记录。</p></div><a href="'+safeLink(RESET_DATA.profile_url)+'" target="_blank" rel="noopener">@thsottiaux '+icon('external')+'</a></div><div class="tibo-signal-list">'+rows.map(x=>'<article class="tibo-signal '+esc(x.evidence_strength||'low')+'"><header><span>'+esc(semanticLabel[x.semantic_type]||RESET_KINDS[x.kind]||'待分类')+'</span><b>证据 '+esc(strengthLabel[x.evidence_strength]||'待评估')+'</b><time>'+esc(when(x))+'</time></header><blockquote>'+esc(x.original_text||x.excerpt||x.summary||'')+'</blockquote><div class="tibo-reading"><strong>我们理解</strong><p>'+esc(x.interpretation||x.summary||'')+'</p></div><div class="tibo-not-proves"><strong>还不能推出</strong><p>'+esc(x.not_proves||x.boundary||x.reason||'需要更多上下文。')+'</p></div><footer>'+(x.url?'<a href="'+safeLink(x.url)+'" target="_blank" rel="noopener">看原帖 '+icon('external')+'</a>':'')+(x._source==='event'?'<button data-ma="reset-detail" data-id="'+esc(x.id)+'">查看记录 '+icon('arrow')+'</button>':'<span>机器候选 · 待核验</span>')+'</footer></article>').join('')+'</div></section>'}
const baseResetPage=resetPage;
resetPage=function(){const html=baseResetPage();const block=intelBlock();return block?html.replace('<div class="m-controls">',block+'<div class="m-controls">'):html};
async function refreshTibo(){if(loading||!['http:','https:'].includes(location.protocol))return;loading=true;try{const u=new URL('api/v1/resets.json',location.href.split('#')[0]);const r=await fetch(u,{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('HTTP '+r.status);const obj=await r.json();if(!obj||!Array.isArray(obj.events)||!Array.isArray(obj.inbox))throw new Error('invalid');RESET_DATA=obj;if(state.view==='tibo'){lastMain='';moduleMain()}}catch(e){console.warn('Tibo snapshot refresh failed',e)}finally{loading=false}}
window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#/tibo'))refreshTibo()});
if(state.view==='tibo')refreshTibo();
})();