'use strict';
/* v1.0: chronological hot stream, Top-5 on the curated landing page, and local personalization. */
const HOT_POLICY=APP.hot_policy||null;
function v10HotByTime(rows){return [...rows].sort((a,b)=>b.published.localeCompare(a.published)||b.heat-a.heat||a.id.localeCompare(b.id))}
function v10HotByHeat(rows){return [...rows].sort((a,b)=>b.heat-a.heat||b.published.localeCompare(a.published)||a.id.localeCompare(b.id))}
hRows=function(){const s=hState(),q=s.q.toLowerCase();return v10HotByTime(HOT.items.filter(x=>(s.cat==='all'||x.category===s.cat)&&(!q||[x.title,x.summary,x.why,x.source,HOT_CATS.get(x.category)?.title].join(' ').toLowerCase().includes(q))))}
function v10Story(x,{rank=null}={}){return `<article class="v10-story">${rank!==null?`<div class="v10-rank">${rank}</div>`:''}<div class="v10-story-main"><div class="h-sub"><span class="h-cat">${icon(H_ICON[x.category]||'sparkles')}${esc(HOT_CATS.get(x.category).title)}</span><span>${esc(x.source)}</span><span class="h-source-kind">${esc(x.source_kind)}</span><time>${esc(x.published)}</time></div><button class="v10-story-title" data-ha="detail" data-id="${x.id}">${esc(x.title)}</button><p>${esc(x.summary)}</p><div class="v10-story-actions"><button data-ha="detail" data-id="${x.id}">为什么值得看 ${icon('arrow')}</button><a href="${safeLink(x.url)}" target="_blank" rel="noopener noreferrer">原始来源 ${icon('external')}</a></div></div><div class="h-heat"><strong>${x.heat}${hTrend(x)}</strong><span>热度</span></div></article>`}
function v10Chronology(rows){const groups={};rows.forEach(x=>(groups[x.published]??=[]).push(x));const entries=Object.entries(groups).sort(([a],[b])=>b.localeCompare(a));return `<div class="v10-chronology">${entries.map(([date,list])=>`<section class="v10-day"><aside><b>${date===HOT.checked?'今天':date.slice(5).replace('-','月')+'日'}</b><span>${date.replaceAll('-','.')}</span></aside><div class="v10-day-items">${list.map(x=>v10Story(x)).join('')}</div></section>`).join('')}</div>`}
hotPage=function(){const s=hState(),rows=hRows();return `<section class="h-wrap v10-hot"><header class="h-head"><div><p class="eyebrow"><span class="accent">●</span> HOT SIGNALS / NEWEST FIRST</p><h1>热点时间线<span class="accent">.</span></h1><p>按发布时间倒序。热度只表示信号强度，不参与时间线排序。</p></div><div class="h-meta"><span><i class="state-dot"></i> 最新优先</span><span>${esc(HOT.checked)}</span><button class="v10-policy-chip" data-ha="method">${HOT_POLICY?.mode==='shadow'?'策略影子评估':'更新策略'}</button></div></header><div class="h-filterbar">${hTabs(s)}<label class="h-search">${icon('search')}<input id="h-search" type="search" value="${esc(s.q)}" placeholder="搜索标题、来源、摘要…" aria-label="搜索热点"><kbd>/</kbd></label></div>${rows.length?v10Chronology(rows):`<div class="h-empty"><h3>没有匹配热点</h3><p>换个关键词或分类。</p></div>`}</section>`}
function v10Top5(){const rows=v10HotByHeat(HOT.items).slice(0,5);return `<section class="v10-top5"><div class="v10-section-head"><div><p class="eyebrow">TOP 5 / CURRENT SIGNALS</p><h2>当前最热</h2></div><a href="#/hot">全部热点 ${icon('arrow')}</a></div><div class="v10-top5-list">${rows.map((x,i)=>`<a href="#/hot?item=${encodeURIComponent(x.id)}"><b>${String(i+1).padStart(2,'0')}</b><span><em>${esc(HOT_CATS.get(x.category).title)}</em>${esc(x.title)}</span><strong>${x.heat}${hTrend(x)}<small>热度</small></strong></a>`).join('')}</div></section>`}
function v10Prefs(){const topics=[...topicFollows],sectors=new Set(topics.map(id=>VTOPICS.get(id)?.sector).filter(Boolean));return {topics:new Set(topics),sectors,models:msaved.size,articles:articleSaved.size}}
function v10TopicFromLink(link=''){try{const raw=String(link||'');const q=raw.split('?')[1]||'';return new URLSearchParams(q).get('topic')}catch{return null}}
function v10PersonalMatch(x,p){const link=x.link||'';if(link.startsWith('#/pharma')){const t=v10TopicFromLink(link);return t?p.topics.has(t):p.sectors.has('pharma')}if(link.startsWith('#/manufacturing')){const t=v10TopicFromLink(link);return t?p.topics.has(t):p.sectors.has('manufacturing')}if(p.models>0&&(x.category==='model'||x.category==='benchmark'||link.startsWith('#/models')||link.startsWith('#/benchmarks')))return true;return false}
function v10PersonalBlock(){const p=v10Prefs();const followed=p.topics.size+p.models;const rows=v10HotByTime(HOT.items.filter(x=>v10PersonalMatch(x,p))).slice(0,5);if(!followed)return `<section class="v10-personal v10-personal-empty"><div><p class="eyebrow">FOR YOU / LOCAL</p><h2>关注以后，这里只放与你有关的热点。</h2><p>你可以关注医药、晶圆厂、装备制造等业务主题，也可以收藏模型。关注保存在当前浏览器。</p></div><div><a class="button" href="#/topics">选择主题</a><a class="button" href="#/models">关注模型</a></div></section>`;return `<section class="v10-personal"><div class="v10-section-head"><div><p class="eyebrow">FOR YOU / ${followed} FOLLOWING</p><h2>为你关注</h2></div><a href="#/topics">管理关注 ${icon('arrow')}</a></div>${rows.length?`<div class="v10-personal-list">${rows.map(x=>v10Story(x)).join('')}</div>`:`<div class="v10-personal-none">当前关注还没有新的热点；不会为了填满页面塞低信号消息。</div>`}</section>`}
function v10GeneralTimeline(){const rows=HOT.items.filter(x=>!AIC_VERTICAL_ONLY.has(x.id));const grouped={};v10HotByTime(rows).forEach(x=>(grouped[x.published]??=[]).push(x));return `<section class="v10-general"><div class="v10-section-head"><div><p class="eyebrow">DAILY / GENERAL AI</p><h2>每日时间线</h2><p>通用 AI 变化按日期排列；垂类内容只有在你关注后才进入“为你关注”。</p></div></div><div class="aic-timeline">${Object.entries(grouped).sort(([a],[b])=>b.localeCompare(a)).map(([date,list])=>`<section class="aic-day"><div class="aic-day-date"><b>${aicDateLabel(date)}</b><span>${date.replaceAll('-','.')}</span></div><div class="aic-day-list">${list.map((x,i)=>`<article class="aic-story"><div class="aic-story-index">${String(i+1).padStart(2,'0')}</div><div class="aic-story-main"><div class="aic-story-meta"><span class="h-cat">${icon(H_ICON[x.category]||'sparkles')}${esc(HOT_CATS.get(x.category).title)}</span><span>${esc(x.source)}</span><span>${esc(x.source_kind)}</span></div><button class="aic-story-title" data-ha="detail" data-id="${x.id}">${esc(x.title)}</button><p>${esc(x.summary)}</p><div class="aic-story-foot"><button data-ha="detail" data-id="${x.id}">为什么值得看 ${icon('arrow')}</button><a href="${safeLink(x.url)}" target="_blank" rel="noopener noreferrer">原始来源 ${icon('external')}</a></div></div><div class="aic-story-heat"><span class="aic-heat-value">${x.heat}</span><span class="aic-heat-label">热度</span>${hTrend(x)}</div></article>`).join('')}</div></section>`).join('')}</div></section>`}
feedPage=function(){return `<div class="v10-feed"><header class="aic-feed-head"><div><p class="eyebrow"><span class="coordinate-dot"></span> 每日精选 / ${esc(HOT.checked.replaceAll('-','.'))}</p><h1>今天，AI 走到哪了？</h1><p>先看全站 Top 5，再看你的关注，最后按时间浏览通用 AI 变化。</p></div><a class="button" href="#/hot">热点时间线 ${icon('arrow')}</a></header>${v10Top5()}${v10PersonalBlock()}${v10GeneralTimeline()}</div>`}
hMethod=function(){const p=HOT_POLICY;showModal('HOT POLICY / UPDATE SCHEDULER',`<h2 id="modal-title">每小时评估，但不是每小时都打扰你。</h2><p class="dialog-intro">${esc(p?.note||'更新策略尚未配置。')}</p><div class="v10-policy-grid"><div><span>决策间隔</span><b>${p?.decision_interval_minutes||'—'} 分钟</b></div><div><span>奖励回看</span><b>${p?.reward_horizon_hours||'—'} 小时</b></div><div><span>当前模式</span><b>${p?.mode==='shadow'?'Shadow / 不自动发布':esc(p?.mode||'—')}</b></div><div><span>学习状态</span><b>${p?.learning?.trained?'已训练':'Bootstrap'}</b></div></div><section class="detail-section"><h3>策略动作</h3><p><strong>Publish</strong>：信号够强，立即更新；<strong>Merge</strong>：中等信号，合并到下一轮；<strong>Hold</strong>：先等热度或证据继续长。</p></section><section class="detail-section"><h3>怎么利用“全天热度”反哺小时决策</h3><p>每个小时只看当时能看到的状态，24 小时后回填最终热度、用户关注匹配、点击/收藏和更新疲劳作为延迟奖励。先用透明权重记录 state → action → reward，积累至少 ${p?.learning?.minimum_feedback_events||'足够多'} 个反馈事件后，再训练 contextual bandit；这样不会一开始就把手写规则冒充成 RL。</p></section><section class="detail-section"><h3>输入特征</h3><div class="v10-feature-list">${(p?.features||[]).map(x=>`<span><b>${esc(x.title)}</b>${esc(x.description)}</span>`).join('')}</div></section><section class="detail-section boundary"><h3>当前边界</h3><p>目前热点内容仍是人工核对快照，策略处于影子模式；它已经定义了每小时是否更新的决策接口，但不会自动把未经核验的候选写成事实。</p></section>`,'hot')}
// Refresh the landing after late overrides are loaded.
if(state.view==='feed'){lastMain='';renderMain()}
