/* FrontierLog topic edition. Local-only preferences; no tracking or hidden requests. */
const VERT=APP.industry, INTAKE=APP.intake;
const VSECTORS=new Map(VERT.sectors.map(s=>[s.id,s]));
const VTOPICS=new Map(VERT.topics.map(t=>[t.id,t]));
const VARTICLES=new Map(VERT.articles.map(a=>[a.id,a]));
const VSOURCES=new Map(VERT.sources.map(s=>[s.id,s]));
const FORMAT={all:'全部',update:'进展与发布',tool:'工具与数据',reference:'基础参考'};
const V_ICON={update:'zap',tool:'wrench',reference:'book',pharma:'pill',manufacturing:'factory'};
const setFrom=(value,allowed)=>new Set(Array.isArray(value)?value.filter(x=>allowed.has(x)):[]);
let topicFollows=setFrom(readStore('frontierlog.topics',[]),VTOPICS);
let articleSaved=setFrom(readStore('frontierlog.articles',[]),VARTICLES);
let vChecks=readStore('frontierlog.article-checks',{});
if(!vChecks||typeof vChecks!=='object'||Array.isArray(vChecks))vChecks={};
const sectorName=id=>VSECTORS.get(id)?.short||'综合';
const topicCount=id=>VERT.articles.filter(a=>a.topics.includes(id)).length;
const topicHref=id=>'#/'+VTOPICS.get(id).sector+'?topic='+encodeURIComponent(id);
const articleDate=a=>a.published?`${a.published.replaceAll('-','.')} 发布`:`常设资料 · ${a.checked.replaceAll('-','.')} 核对`;
function vButton(label,action,id='',extra=''){return `<button class="v-button ${extra}" data-va="${action}" data-id="${esc(id)}">${label}</button>`}
function followButton(id){const yes=topicFollows.has(id);return `<button class="topic-follow ${yes?'is-followed':''}" data-va="follow" data-id="${id}" aria-pressed="${yes}" aria-label="${yes?'取消关注':'关注'}${esc(VTOPICS.get(id).title)}">${icon(yes?'check':'plus')}<span>${yes?'已关注':'关注'}</span></button>`}
function vSave(a){const yes=articleSaved.has(a.id);return `<button class="v-save ${yes?'is-saved':''}" data-va="save" data-id="${a.id}" aria-label="${yes?'取消收藏':'收藏'}：${esc(a.title)}" aria-pressed="${yes}">${icon('bookmark')}</button>`}
function vSourceRows(ids){return ids.map(id=>{const s=VSOURCES.get(id);if(!s)return '';return `<div class="source-row"><a href="${safeLink(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ${icon('external')}</a><small>${esc(s.publisher)} · ${esc(s.kind)}<br>发布：${s.published||s.date_label||'未标单一日期'} · 资料核对：${s.checked}</small></div>`}).join('')}
function filterArticles({sector=null,topic=state.topic,format=state.format,q=state.q,focus=state.focus}={}){
 const query=(q||'').trim().toLowerCase();
 let rows=VERT.articles.filter(a=>(!sector||a.sector===sector)&&(topic==='all'||a.topics.includes(topic))&&(format==='all'||a.kind===format)&&(!focus||a.topics.some(t=>topicFollows.has(t)))&&(!query||[a.title,a.summary,a.why,a.access,...a.topics.map(t=>VTOPICS.get(t).title),...a.sources.map(s=>VSOURCES.get(s).publisher)].join(' ').toLowerCase().includes(query)));
 if(state.sort==='curated'){const order=['ot-release-2606','yseop-csr','lam-ei','extractai-inspection','anomalib-inspection'];rows.sort((a,b)=>{const rank=x=>order.includes(x.id)?order.indexOf(x.id):100+VERT.articles.indexOf(x);return rank(a)-rank(b)})}
 if(state.sort==='events')rows.sort((a,b)=>(b.published||'').localeCompare(a.published||''));
 if(state.sort==='name')rows.sort((a,b)=>a.title.localeCompare(b.title,'zh-CN'));
 if(state.sort==='sources')rows.sort((a,b)=>b.sources.length-a.sources.length);
 return rows;
}
function articleCard(a){const first=VSOURCES.get(a.sources[0]);return `<article class="v-article" data-article-id="${a.id}"><div class="v-article-meta"><span class="v-type type-${a.kind} label-icon">${icon(V_ICON[a.kind]||'book')}${FORMAT[a.kind]}</span><span>${esc(first.publisher)}</span><span class="v-pubdate">${articleDate(a)}</span></div><div class="v-title-row"><button class="v-article-title" data-va="article" data-id="${a.id}">${esc(a.title)}</button>${vSave(a)}</div><p class="v-summary">${esc(a.summary)}</p><div class="v-why"><span>为什么关注</span><p>${esc(a.why)}</p></div><div class="v-article-footer"><div class="v-tags">${a.topics.map(t=>`<a href="${topicHref(t)}">${esc(VTOPICS.get(t).title)}</a>`).join('')}</div><div class="v-article-actions"><a href="${safeLink(first.url)}" target="_blank" rel="noopener noreferrer">原始来源 ${icon('external')}</a><button data-va="article" data-id="${a.id}">证据与边界 ${icon('arrow')}</button></div></div></article>`}
function vEmpty(message='试试其他主题或关键词，或者清除筛选。'){return `<div class="v-empty">${icon('search')}<h3>没有符合条件的资料</h3><p>${message}</p>${vButton('清除筛选','reset')}</div>`}
function sectorCards(){return `<div class="sector-gateways">${VERT.sectors.map(s=>`<a class="sector-gateway ${s.id}" href="#/${s.id}"><div class="gateway-top"><span class="label-icon">${icon(V_ICON[s.id]||'layers')}${s.eyebrow}</span>${icon('arrow')}</div><h3>${s.title}</h3><p>${s.id==='pharma'?'靶点 · 分子 · 临床 · CSR':'晶圆厂 · 工艺 · 装备 · 数字孪生'}</p></a>`).join('')}</div>`}
function topicHub(){return `<div class="v-pagehead"><div><p class="eyebrow">TOPIC DIRECTORY / BY WORKFLOW</p><h1>按你的行业，追踪进展。</h1><p class="v-lead">不是把 AI 新闻换个标签，而是沿业务环节看能力、工具和证据。</p></div>${vButton('一键关注重点主题','follow-recommended','','primary')}</div><div class="topic-hub-grid">${VERT.sectors.map(s=>`<section class="topic-sector ${s.id}"><div class="topic-sector-head"><div><span class="eyebrow">${s.eyebrow}</span><h2><a href="#/${s.id}">${s.title} ${icon('arrow')}</a></h2></div><span class="v-count">${VERT.topics.filter(t=>t.sector===s.id).length} 个主题</span></div><p class="sector-desc">${s.description}</p>${s.groups.map(g=>`<h3 class="v-group-title">${g}</h3><div class="topic-rows">${VERT.topics.filter(t=>t.sector===s.id&&t.group===g).map(t=>`<div class="topic-row"><a href="${topicHref(t.id)}"><strong>${t.title}</strong><p>${t.description}</p><span>${topicCount(t.id)} 条资料</span></a>${followButton(t.id)}</div>`).join('')}</div>`).join('')}<div class="sector-note">${s.note}</div></section>`).join('')}</div><div class="v-bottom-note">关注保存在当前浏览器；主题 RSS 可以复制到阅读器。${vButton('导出我的主题','export-personal')}${vButton('导入关注','import-personal')}</div>`}
function topicStrip(sector){const ts=VERT.topics.filter(t=>t.sector===sector);return `<div class="v-topic-strip"><a class="${state.topic==='all'?'active':''}" href="#/${sector}">全部主题</a>${ts.map(t=>`<a class="${state.topic===t.id?'active':''}" href="${topicHref(t.id)}">${t.title}<span>${topicCount(t.id)}</span></a>`).join('')}</div>`}
function topicHeader(sector){const s=VSECTORS.get(sector);const t=VTOPICS.get(state.topic);const rows=VERT.articles.filter(a=>a.sector===sector);const featured=sector==='pharma'?VARTICLES.get('yseop-csr'):VARTICLES.get('lam-ei');return `<div class="v-sector-hero"><div class="v-sector-copy"><p class="eyebrow"><a href="#/topics">垂类主题</a> / ${t?`${s.title} / ${t.group}`:s.eyebrow}</p><h1>${t?t.title:s.title}</h1><p class="v-lead">${t?t.description:s.description}</p><div class="v-sector-stats"><span><b>${t?topicCount(t.id):rows.length}</b> 条资料</span><span><b>${new Set((t?rows.filter(a=>a.topics.includes(t.id)):rows).flatMap(a=>a.sources)).size}</b> 个原始来源</span><span>核对 ${VERT.checked.replaceAll('-','.')}</span></div><div class="v-hero-actions">${t?followButton(t.id):vButton('关注整个领域','follow-sector',sector,'primary')}${vButton(icon('rss')+' 主题 RSS','rss',t?t.id:sector)}${vButton(icon('download')+' 导出专题','export-topic')}</div></div><button class="v-spotlight ${sector}" data-va="article" data-id="${featured.id}"><div><span class="spotlight-kicker">本期重点 / ${sector==='pharma'?'CSR':'FAB'}</span><span class="spotlight-no">01</span></div><h2>${sector==='pharma'?'从自动成稿，<br>走向来源可追溯。':'让设备数据，<br>进入维护与控制。'}</h2><p>${sector==='pharma'?'医学写作 · 来源核对 · 人工审核':'工艺数据 · 异常诊断 · 设备维护'}</p><footer><span>${sector==='pharma'?'Yseop / MedWriter.ai':'Lam Equipment Intelligence'}</span>${icon('arrow')}</footer></button></div>${topicStrip(sector)}`}
function vToolbar(){return `<div class="v-toolbar"><div class="v-format-tabs">${Object.entries(FORMAT).map(([k,label])=>`<button class="${state.format===k?'active':''}" data-va="format" data-id="${k}" aria-pressed="${state.format===k}">${label}</button>`).join('')}</div><div class="v-filter-controls"><label class="v-search">${icon('search')}<input type="search" id="v-search" aria-label="搜索行业资料" placeholder="搜索主题、工具、公司…" value="${esc(state.q)}"></label><select id="v-sort" aria-label="专题排序"><option value="curated" ${state.sort==='curated'?'selected':''}>精选顺序</option><option value="events" ${state.sort==='events'?'selected':''}>发布日期</option><option value="sources" ${state.sort==='sources'?'selected':''}>来源数量</option></select></div></div><div class="v-result-meta"><span>公开资料整理 · 历史日期保留 · 未代替实测</span><label><input id="v-focus" type="checkbox" ${state.focus?'checked':''}> 只看已关注主题</label></div>`}
const TOPIC_QUESTIONS={targets:['证据来自计算、实验，还是临床？','能否定位到原始研究和样本条件？'],molecules:['预测有没有外部实验支持？','开放的是代码、权重，还是在线接口？'],clinical:['试验注册和结果披露是否区分？','记录版本与 NCT 标识能否追溯？'],csr:['每段结论能否回到 Protocol / SAP / TLF？','数字、表格、正文和版本是否一致？','谁审阅，谁批准，改了什么？'],'fab-yield':['能否区分漏检、误报与复检成本？','换产品、换工艺之后还有效吗？'],'fab-process':['监测、诊断、控制是否分开验证？','离线验证后怎样进入受控生产？'],'fab-maintenance':['支持哪些机台与腔体？','返工、停机与安全如何验收？'],'equipment-design':['生成代码在仿真中验证了吗？','生产联锁和工程审批如何处理？'],'equipment-maintenance':['检测结果能否关联真实维修记录？','新批次和新设备上如何复验？'],'digital-twin':['仿真与现场偏差怎样量化？','布局、物流与传感器假设是否明确？']};
function vRail(sector,rows){const t=VTOPICS.get(state.topic);const questions=t?TOPIC_QUESTIONS[t.id]:(!sector?['按业务环节分类，不按热度堆叠。','看清公开实现、商业产品与研究材料。','先回原始来源，再决定是否试用。']:sector==='pharma'?['靶点：从关联到验证，证据在哪一步？','CSR：从输入文件到结论，能否追溯？','工具：公开入口与商业演示分开看。']:['晶圆厂：工艺、良率、设备分开看。','装备：设计、维护、仿真分开验收。','案例：厂商说明不冒充独立实测。']);const ids=[...new Set(rows.flatMap(a=>a.sources))];return `<aside class="v-rail"><section class="v-rail-panel"><span class="eyebrow">RESEARCH LENS</span><h3>带着问题看进展</h3>${questions.map((q,i)=>`<div class="lens-row"><span>0${i+1}</span><p>${q}</p></div>`).join('')}</section><section class="v-rail-panel"><div class="rail-heading"><h3>原始信源</h3><span>${ids.length}</span></div>${ids.slice(0,4).map(id=>{const s=VSOURCES.get(id);return `<a class="rail-source" href="${safeLink(s.url)}" target="_blank" rel="noopener noreferrer"><span>${esc(s.publisher)}<small>${esc(s.kind)}</small></span>${icon('external')}</a>`}).join('')}${vButton('查看本页全部来源','page-sources')}</section><section class="v-rail-panel v-rail-follow"><h3>把这个领域留下来</h3><p>下次从你关注的业务环节开始。</p>${vButton('管理我的主题','my-topics','','primary')}<small>本机保存，不发送邮件或通知</small></section></aside>`}
function feedPage(){const rows=filterArticles();return `<div class="v-home-intro"><p class="eyebrow">AI坐标 / 每日精选 · ${VERT.checked.replaceAll('-','.')}</p><h1>看进展。<span>更看你的行业。</span></h1><p class="v-lead">AI 的新能力、落地状态和使用入口。聚焦医药、制造业，也看模型与评测。</p></div>${sectorCards()}<div class="v-fastlinks"><a href="#/progress"><span class="mini-icon">${icon('zap')}</span><strong>AI 又能干什么了</strong><small>按任务看能力</small>${icon('arrow')}</a><a href="#/activity"><span class="mini-icon">${icon('history')}</span><strong>发布会之后</strong><small>保留发布与变化</small>${icon('arrow')}</a><a href="#/toolkit"><span class="mini-icon">${icon('wrench')}</span><strong>今天能跑</strong><small>工具与上手路径</small>${icon('arrow')}</a></div><div class="v-sectionline"><h2>${icon('sparkles')}本期精选</h2><span>主题资料，不冒充实时热榜</span></div>${vToolbar()}<div class="v-feed-layout"><div class="v-article-list">${rows.length?rows.map(articleCard).join(''):vEmpty()}</div>${vRail(null,rows)}</div>`}
function sectorPage(sector){const rows=filterArticles({sector});return `${topicHeader(sector)}${vToolbar()}<div class="v-feed-layout"><div class="v-article-list">${rows.length?rows.map(articleCard).join(''):vEmpty()}</div>${vRail(sector,rows)}</div><div class="v-bottom-note">${VSECTORS.get(sector).note}</div>`}
function signalsPage(){return `<div class="v-pagehead"><div><p class="eyebrow">SOURCE INBOX / UNREVIEWED</p><h1>先收集线索，再形成结论。</h1><p class="v-lead">自动采集与人工专题分开。机器命中的条目不会自动变成“已验证”。</p></div>${vButton('查看采集状态','sync')}</div><div class="v-status-grid"><div><span>最后尝试</span><strong>${esc(INTAKE.last_attempt||'尚未运行')}</strong></div><div><span>最近有源成功</span><strong>${esc(INTAKE.last_success||'尚未运行')}</strong></div><div><span>待核验线索</span><strong>${INTAKE.items.length}</strong></div></div>${INTAKE.items.length?INTAKE.items.map(i=>`<article class="v-article"><div class="v-article-meta"><span class="v-type">自动收录 · 待核验</span><span>${esc(i.publisher)}</span><span>${esc(i.published_at||'未标发布日期')}</span></div><h3><a href="${safeLink(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.title)} ${icon('external')}</a></h3><p class="v-summary">${esc(i.excerpt||'仅收录标题与链接，未生成效果结论。')}</p><div class="v-tags">${i.topics.map(id=>`<a href="${topicHref(id)}">${VTOPICS.get(id).title}</a>`).join('')}</div></article>`).join(''):`<div class="v-empty">${icon('rss')}<h3>首次采集尚未执行</h3><p>当前显示人工整理的专题资料。采集脚本与工作流在源码包中；上传静态页面不会自动开启定时采集。</p>${vButton('查看更新机制','sync')}</div>`}`}
function renderVerticalMain(){lastMain='';$('#hero').hidden=true;$('#stats').hidden=true;$('.workspace').hidden=true;$('#legacy-saved').innerHTML='';const root=$('#vertical-root');root.hidden=false;root.innerHTML=state.view==='topics'?topicHub():state.view==='feed'?feedPage():state.view==='signals'?signalsPage():sectorPage(state.view);}
function showArticle(id){const a=VARTICLES.get(id);if(!a)return;const first=VSOURCES.get(a.sources[0]);showModal('TOPIC FILE / '+sectorName(a.sector),`<div class="v-detail-meta"><span class="v-type type-${a.kind} label-icon">${icon(V_ICON[a.kind]||'book')}${FORMAT[a.kind]}</span><span>${a.access}</span>${vSave(a)}</div><h2 id="modal-title">${esc(a.title)}</h2><p class="v-detail-date">${articleDate(a)} · 本站未实测</p><section class="detail-section"><h3>资料说了什么</h3><p>${esc(a.summary)}</p><div class="v-inline-source"><a href="${safeLink(first.url)}" target="_blank" rel="noopener noreferrer">${esc(first.publisher)} · 原文 ${icon('external')}</a></div></section><section class="detail-section v-editorial"><h3>为什么值得看 · 编辑解读</h3><p>${esc(a.why)}</p></section><section class="detail-section boundary"><h3>哪些结论还不能下</h3><p>${esc(a.boundary)}</p></section><section class="detail-section"><h3>建议从这里开始 · 非已完成实测</h3><ol class="v-steps">${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section class="detail-section"><h3>你的检查清单</h3><div class="checklist">${a.metrics.map((m,i)=>`<label><input type="checkbox" data-v-check="${a.id}" data-index="${i}" ${vChecks[a.id]?.includes(i)?'checked':''}>${esc(m)}</label>`).join('')}</div><p class="detail-notice">本机勾选不会改变网站的证据标签。</p></section><div class="v-tags">${a.topics.map(t=>`<button data-va="open-topic" data-id="${t}">${VTOPICS.get(t).title} ↗</button>`).join('')}</div><div class="action-row"><a class="button primary" href="${safeLink(first.url)}" target="_blank" rel="noopener noreferrer">官方入口 ${icon('external')}</a><button class="button" data-va="share-article" data-id="${id}">复制档案链接</button><button class="button" data-va="export-article" data-id="${id}">导出笔记</button></div><details class="source-accordion" open><summary>原始来源 <span>${a.sources.length}</span></summary>${vSourceRows(a.sources)}</details>`,'article')}
function myTopics(){showModal('PERSONAL / TOPICS',`<h2 id="modal-title">只留下你关心的环节。</h2><p class="dialog-intro">当前关注 ${topicFollows.size} 个主题。保存在本机，不创建远程账号。</p><div class="v-manage-topics">${VERT.topics.map(t=>`<div class="topic-row"><a href="${topicHref(t.id)}" data-va="open-topic" data-id="${t.id}"><strong>${t.title}</strong><p>${sectorName(t.sector)} / ${t.group}</p></a>${followButton(t.id)}</div>`).join('')}</div><div class="action-row">${vButton('备份关注与笔记','export-personal','','primary')}${vButton('导入备份','import-personal')}${vButton('查看我的收藏','open-saved')}</div>`,'manage-topics')}
function renderSavedVertical(){const a=VERT.articles.filter(x=>articleSaved.has(x.id));$('#legacy-saved').innerHTML=`<section class="v-personal"><div class="v-sectionline"><h2>我的主题与资料</h2>${vButton('管理主题 · '+topicFollows.size,'my-topics')}</div><div class="v-tags">${[...topicFollows].map(id=>`<a href="${topicHref(id)}">${VTOPICS.get(id).title}</a>`).join('')||'<span class="muted">还没有关注主题</span>'}</div><div class="v-article-list">${a.length?a.map(articleCard).join(''):'<p class="v-bottom-note">在专题卡片上点收藏，把资料保存在这里。下方继续保留原有项目关注。</p>'}</div></section>`}
function topicRss(id){const scope=VTOPICS.get(id)?.title||VSECTORS.get(id)?.title||'全部专题';const url=SITE.base_url+'feeds/'+(id||'all')+'.xml';showModal('SUBSCRIBE / '+scope,`<h2 id="modal-title">订阅 ${esc(scope)}</h2><p class="dialog-intro">阅读器获取这个主题的已编选资料；不会自动订阅你的邮箱。</p><div class="codebox"><pre>${esc(url)}</pre></div><div class="action-row">${vButton('复制 RSS 地址','copy-rss',id,'primary')}<a class="button" href="${safeLink(url)}" target="_blank" rel="noopener noreferrer">打开 RSS ${icon('external')}</a></div><p class="detail-notice">本包生成的是当前资料快照。只有采集、编选与重新部署链路运行后，远程订阅内容才会变化。未标发布日期的常设资料不伪装成今日新闻。</p>`)}
function syncInfo(){showModal('PIPELINE / STATUS',`<h2 id="modal-title">采集，不等于核验。</h2><p class="dialog-intro">公开来源 → 去重 → 主题规则 → 待核验线索 → 人工编选 → 发布。</p><div class="health-row"><span>人工专题核对</span><span>${VERT.checked}</span></div><div class="health-row"><span>最后采集尝试</span><span>${esc(INTAKE.last_attempt||'尚未执行')}</span></div><div class="health-row"><span>最近全部信源成功</span><span>${esc(INTAKE.last_full_success||'尚无记录')}</span></div>${INTAKE.sources.map(s=>`<div class="health-row"><span>${esc(s.name)}</span><span>${esc(s.status)}</span></div>`).join('')}<section class="detail-section"><h3>这一版已实现</h3><p>两大行业、十个主题、资料类型筛选、主题关注、来源档案、专题 RSS 和自动线索入口。源码包含 RSS / Atom / GitHub Releases 采集、去重与分类规则。</p></section><section class="detail-section boundary"><h3>部署边界</h3><p>静态上传包不启动定时任务。完整源码需要上传工作流并将 Pages 发布源切换为 GitHub Actions；首次运行、外网采集与权限仍需在仓库中验收。</p><p>机器候选不自动生成疗效、良率或监管接受结论，也不会自动进入人工精选。</p></section><p class="detail-notice">前端不直接访问临床或工厂数据；不要提交患者信息、未公开 CSR、晶圆生产日志或访问密钥。</p>`)}
function pageSources(){const rows=filterArticles({sector:VSECTORS.has(state.view)?state.view:null});const ids=[...new Set(rows.flatMap(a=>a.sources))];showModal('SOURCES / '+ids.length,`<h2 id="modal-title">本页的原始资料</h2><p class="dialog-intro">来源核对时间与原始发布时间分别记录。</p>${vSourceRows(ids)}`)}
function articleText(a){return `# ${a.title}\n\n主题：${a.topics.map(t=>VTOPICS.get(t).title).join(' / ')}\n发布：${a.published||'未标单一日期'}；核对：${a.checked}\n\n## 资料概述\n${a.summary}\n\n## 编辑解读\n${a.why}\n\n## 边界\n${a.boundary}\n\n## 建议核验（不是已完成实测）\n${a.metrics.map(m=>'- [ ] '+m).join('\n')}\n\n## 原始来源\n${a.sources.map(s=>'['+VSOURCES.get(s).title+']('+VSOURCES.get(s).url+')').join('\n')}\n`}
function exportVertical(){const list=state.view==='signals'?INTAKE.items:filterArticles({sector:VSECTORS.has(state.view)?state.view:null});download('frontierlog-'+state.view+'.json',JSON.stringify({checked:VERT.checked,view:state.view,topic:state.topic,items:list,topics:VERT.topics,sources:VERT.sources},null,2),'application/json;charset=utf-8')}
function exportPersonal(){download('frontierlog-personal.json',JSON.stringify({version:1,topics:[...topicFollows],articles:[...articleSaved],article_checks:vChecks,legacy:{saved:[...saved],checks}},null,2),'application/json;charset=utf-8')}
function rerenderVertical(){lastMain='';renderMain();if(state.article)showArticle(state.article);if(modal.open&&modal.dataset.type==='manage-topics')myTopics()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-va]');if(!b)return;const a=b.dataset.va,id=b.dataset.id;e.preventDefault();
 if(a==='article')return writeRoute({article:id,task:null});
 if(a==='open-topic'){hideModal(false);return writeRoute({view:VTOPICS.get(id).sector,topic:id,q:'',article:null,task:null,format:'all'})}
 if(a==='format')return writeRoute({format:id,article:null},true);
 if(a==='reset')return writeRoute({q:'',format:'all',topic:'all',focus:false,sort:'curated'},true);
 if(a==='follow'){topicFollows.has(id)?topicFollows.delete(id):topicFollows.add(id);const ok=store('frontierlog.topics',[...topicFollows]);rerenderVertical();toast(ok?'主题关注已保存到本机':'本次页面已更新；浏览器不允许持久保存');return}
 if(a==='follow-sector'||a==='follow-recommended'){const ids=a==='follow-sector'?VERT.topics.filter(t=>t.sector===id).map(t=>t.id):['targets','csr','fab-process','fab-maintenance','equipment-design','equipment-maintenance'];ids.forEach(t=>topicFollows.add(t));const ok=store('frontierlog.topics',[...topicFollows]);rerenderVertical();toast(ok?'主题已加入本机关注':'已关注；仅在本次页面有效');return}
 if(a==='save'){articleSaved.has(id)?articleSaved.delete(id):articleSaved.add(id);const ok=store('frontierlog.articles',[...articleSaved]);rerenderVertical();toast(ok?'收藏已更新（本机）':'已更新；仅在本次页面有效');return}
 if(a==='my-topics')return myTopics();
 if(a==='open-saved'){hideModal(false);return writeRoute({view:'saved',task:null,article:null,q:'',topic:'all'})}
 if(a==='rss')return topicRss(id);
 if(a==='copy-rss')return copyText(SITE.base_url+'feeds/'+(id||'all')+'.xml');
 if(a==='page-sources')return pageSources();
 if(a==='sync')return syncInfo();
 if(a==='export-personal')return exportPersonal();
 if(a==='import-personal'){$('#vertical-import').click();return}
 if(a==='export-topic')return exportVertical();
 if(a==='export-article')return download('frontierlog-'+id+'.md',articleText(VARTICLES.get(id)));
 if(a==='share-article')return copyText(SITE.base_url+'#/'+VARTICLES.get(id).sector+'?article='+id);
});
document.addEventListener('input',e=>{if(e.target.id!=='v-search')return;const value=e.target.value;const pos=e.target.selectionStart;writeRoute({q:value},true);const input=$('#v-search');input?.focus({preventScroll:true});try{input.setSelectionRange(pos,pos)}catch{}});
document.addEventListener('change',e=>{if(e.target.id==='v-sort')writeRoute({sort:e.target.value},true);if(e.target.id==='v-focus')writeRoute({focus:e.target.checked},true);if(e.target.matches('[data-v-check]')){const id=e.target.dataset.vCheck;const n=Number(e.target.dataset.index);const values=new Set(vChecks[id]||[]);e.target.checked?values.add(n):values.delete(n);vChecks[id]=[...values];store('frontierlog.article-checks',vChecks)}});
$('#vertical-import').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>500000)return toast('备份文件过大');try{const o=JSON.parse(await f.text());if(o.version!==1||!Array.isArray(o.topics)||!Array.isArray(o.articles))throw Error();setFrom(o.topics,VTOPICS).forEach(t=>topicFollows.add(t));setFrom(o.articles,VARTICLES).forEach(a=>articleSaved.add(a));if(o.article_checks&&typeof o.article_checks==='object')for(const [id,list] of Object.entries(o.article_checks)){if(VARTICLES.has(id)&&Array.isArray(list))vChecks[id]=[...new Set(list.filter(n=>Number.isInteger(n)&&n>=0&&n<VARTICLES.get(id).metrics.length))]}if(o.legacy?.saved)setFrom(o.legacy.saved,tasks).forEach(id=>saved.add(id));if(o.legacy?.checks&&typeof o.legacy.checks==='object')for(const [id,list] of Object.entries(o.legacy.checks)){if(tasks.has(id)&&Array.isArray(list))checks[id]=[...new Set(list.filter(n=>Number.isInteger(n)&&n>=0&&n<tasks.get(id).checks.length))]}store('aip.checks',checks);let ok=store('frontierlog.topics',[...topicFollows]);ok=store('frontierlog.articles',[...articleSaved])&&ok;ok=store('frontierlog.article-checks',vChecks)&&ok;store('aip.saved',[...saved]);rerenderVertical();toast(ok?'已合并主题、收藏和检查清单':'已合并；浏览器不允许持久保存')}catch{toast('文件格式不正确，请使用本站的主题备份')}});
// The global source directory includes new sources without mutating old task data.
allSources=function(){showModal('SOURCES / PRIMARY MATERIAL',`<h2 id="modal-title">每条资料，都能回到原文。</h2><h3 class="v-group-title">垂类主题 · ${VERT.sources.length} 个来源</h3>${vSourceRows(VERT.sources.map(s=>s.id))}<h3 class="v-group-title">原有任务档案 · ${DATA.sources.length} 个来源</h3>${sourceRows(DATA.sources.map(s=>s.id))}`)};
/* Bootstrap follows in models.js. */
